# Generated by Django 5.0 on 2025-06-27 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_combine_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
